// examples/template-ssr-solid-ts/src/App.tsx
import { createSignal } from "solid-js"
import "./App.css"

function App({ time }: { time: string }) {
	const [count, setCount] = createSignal(0)

	return (
		<div class="App">
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src="/vite.svg" class="logo" alt="Vite logo" />
				</a>
				<a href="https://www.solidjs.com" target="_blank">
					<img src="/solid.svg" class="logo solid" alt="Solid logo" />
				</a>
			</div>
			<h1>Vite + Solid</h1>
			<div class="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count()}
				</button>
				<p>
					Edit <code>src/App.tsx</code> and save to test HMR
				</p>
			</div>
			<p class="read-the-docs">
				Click on the Vite and Solid logos to learn more
			</p>
			<p>Server time: {time}</p>
		</div>
	)
}

export default App

// examples/template-ssr-preact-ts/src/app.tsx
import { useState } from "preact/hooks"
import "./app.css"

export function App({ time }: { time: string }) {
	const [count, setCount] = useState(0)

	return (
		<>
			<div>
				<a href="https://vitejs.dev" target="_blank">
					<img src="/vite.svg" class="logo" alt="Vite logo" />
				</a>
				<a href="https://preactjs.com" target="_blank">
					<img src="/preact.svg" class="logo preact" alt="Preact logo" />
				</a>
			</div>
			<h1>Vite + Preact</h1>
			<div class="card">
				<button onClick={() => setCount((count) => count + 1)}>
					count is {count}
				</button>
				<p>
					Edit <code>src/app.tsx</code> and save to test HMR
				</p>
			</div>
			<p class="read-the-docs">
				Click on the Vite and Preact logos to learn more
			</p>
			<p>This time came from the server: {time}</p>
		</>
	)
}
